---

version: '3'

services: 
  app:
    env_file: .env
    build: ./docker/nodejs
    restart: "no"
    entrypoint: sh /bin/entrypoint.sh
    expose: 
      - 3000
      - 24678
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./docker/nodejs/entrypoint.sh:/bin/entrypoint.sh
      - /var/www/html/app/node_modules
    networks: 
      - sveltekit-wordpress

  fpm:
    build:
      context: ./
      dockerfile: ./docker/fpm/fpm.Dockerfile

    ports:
      - 9000:9000

    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - "./:/var/www/html"
      - "./docker/fpm/wp-config.php:/var/www/html/cms/wp-config.php"
      - "./docker/fpm/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
    networks: 
      - sveltekit-wordpress

  nginx:
    image: nginx:latest
    ports: 
      - 80:80
      - 3000:3000
      - 24678:24678
    volumes: 
      - "./:/var/www/html"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro"
    networks: 
      - sveltekit-wordpress

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks: 
      - sveltekit-wordpress

  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    ports: 
      - '3030:80'
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - sveltekit-wordpress

volumes:
  mysql: {}

networks: 
  sveltekit-wordpress:
    external: false