---

version: '3'

services: 
  app:
    image: node:14.17.4
    command: bash -c 'cd ./app; npm install && npm run dev'
    build: ./app
    volumes: 
      - "./app:/app"
    networks: 
      - sveltekit-wordpress

  fpm:
    build:
      context: ./
      dockerfile: ./docker/fpm/fpm.Dockerfile

    ports:
      - 9000:9000

    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

    volumes:
      - "./:/var/www/html"
      - "./docker/fpm/wp-config.php:/var/www/html/cms/wp-config.php"
      - "./docker/fpm/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
    networks: 
      - sveltekit-wordpress

  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes: 
      - "./:/var/www/html"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro"
    networks: 
      - sveltekit-wordpress

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    networks: 
      - sveltekit-wordpress

  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    ports: 
      - '3030:80'
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - sveltekit-wordpress

volumes:
  mysql: {}

networks: 
  sveltekit-wordpress:
    external: false