---

version: '3'

services: 
  app:
    image: node:14.17.4
    command: bash -c 'npm install && npm run dev'
    volumes: 
      - "./:/app"
    networks: 
      - sveltekit-wordpress

  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
      - "4000:80"
    volumes: 
      - "./cms:/var/www/html/cms"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro"
    networks: 
      - sveltekit-wordpress

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_ROOTPASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    networks: 
      - sveltekit-wordpress

  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    ports: 
      - '3030:80'
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - sveltekit-wordpress

volumes:
  mysql: {}

networks: 
  sveltekit-wordpress:
    external: false